apiVersion: v1
kind: Namespace
metadata:
  name: dfgdfgdf-prod
  labels:
    environment-id: env_5608da2c-91fd-4fa9-993c-d577e9cd90e0
    project-id: project_4a080985-672f-4f98-b545-d57cbfde966b
    project-name: dfgdfgdf
    environment-name: prod
    organization-id: org_1c58789b-c98c-4917-b321-116968ec4f8e
